<a href="https://colab.research.google.com/github/CheeHoong0402/data-science-toolkit/blob/main/LoanPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

------------Tutorial 03-------------------

#Tidy Data, Data Characteristics

1. Find some real dataset. Load it on Colab, Kaggle etc. Try to visualize some of it

2. Evaluate if the data is good or not. Does it have enough samples?

3. How many features does it have? Is it enough?

4. How many samples/observation does it have? Is it enough?

5. What are the datatypes does the dataset consist of?

6. How many columns have null values? If yes, which column, which rows

7. Which column is the feature, which is the target output?

8. Does it have missing values? If yes, which column, which row.

9. What kind of question can be asked, should we ask. Does the dataset suits the question we are asking?

In [10]:
import pandas as pd

df = pd.read_csv('/content/loan_train.csv')
display(df)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [17]:
# 2. Evaluate if the data is good or not. Does it have enough samples?

print("Rows and columns: ", df.shape)
print("Repeated loan ID: ", df['Loan_ID'].duplicated().sum())
print("Loan status(N = Unsuccessful, Y = Successful)")
print(df['Loan_Status'].value_counts())

Rows and columns:  (614, 13)
Repeated loan ID:  0
Loan status(N = Unsuccessful, Y = Successful)
Loan_Status
Y    422
N    192
Name: count, dtype: int64

In [15]:
print("All colums: ")
print(df.columns.tolist())
print("Number of columns:", len(df.columns))
print("Possible input columns (excluding Loan_Status):", len(df.columns) - 1)

All colums:
['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status']
Number of columns: 13
Possible input columns (excluding Loan_Status): 12

In [16]:
print("Number of applicants: ", len(df))

Number of applicants:  614

In [20]:
print(df.dtypes)

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [26]:
missing = df.isnull().sum()
print("Missing values in each columns")
print(missing)
print("\nColumns with any missing values:")
print(missing[missing > 0])
print("\nNumber of columns with missing values:", (missing > 0).sum())

Missing values in each columns
Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

Columns with any missing values:
Gender              13
Married              3
Dependents          15
Self_Employed       32
LoanAmount          22
Loan_Amount_Term    14
Credit_History      50
dtype: int64

Number of columns with missing values: 7

In [27]:
target = "Loan_Status"
features = df.drop(columns = ["Loan_Status", "Loan_ID"])

print("Target: ", target)
print("Example features columns: ", features.columns.tolist())
print("Target values:", df[target].unique())

Target:  Loan_Status
Example features columns:  ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area']
Target values: ['Y' 'N']

In [36]:
rows_missing = df[df.isnull().any(axis=1)]
print("Number of rows with at least one missing value:", len(rows_missing))
print("First 10 rows containing missing values:")
display(rows_missing.head(10))

for column in rows_missing.columns:
    for row in rows_missing.index[rows_missing[column].isnull()]:
        print(f"Row: {row}, Column: {column}")

Number of rows with at least one missing value: 134
First 10 rows containing missing values:

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
30,LP001091,Male,Yes,1,Graduate,NaN,4166,3369.0,201.0,360.0,NaN,Urban,N
35,LP001106,Male,Yes,0,Graduate,No,2275,2067.0,NaN,360.0,1.0,Urban,Y
36,LP001109,Male,Yes,0,Graduate,No,1828,1330.0,100.0,NaN,0.0,Urban,N

Row: 23, Column: Gender
Row: 126, Column: Gender
Row: 171, Column: Gender
Row: 188, Column: Gender
Row: 314, Column: Gender
Row: 334, Column: Gender
Row: 460, Column: Gender
Row: 467, Column: Gender
Row: 477, Column: Gender
Row: 507, Column: Gender
Row: 576, Column: Gender
Row: 588, Column: Gender
Row: 592, Column: Gender
Row: 104, Column: Married
Row: 228, Column: Married
Row: 435, Column: Married
Row: 102, Column: Dependents
Row: 104, Column: Dependents
Row: 120, Column: Dependents
Row: 226, Column: Dependents
Row: 228, Column: Dependents
Row: 293, Column: Dependents
Row: 301, Column: Dependents
Row: 332, Column: Dependents
Row: 335, Column: Dependents
Row: 346, Column: Dependents
Row: 355, Column: Dependents
Row: 435, Column: Dependents
Row: 517, Column: Dependents
Row: 571, Column: Dependents
Row: 597, Column: Dependents
Row: 11, Column: Self_Employed
Row: 19, Column: Self_Employed
Row: 24, Column: Self_Employed
Row: 29, Column: Self_Employed
Row: 30, Column: Self_Employed
Row: 95, Column: Self_Employed
Row: 107, Column: Self_Employed
Row: 111, Column: Self_Employed
Row: 114, Column: Self_Employed
Row: 158, Column: Self_Employed
Row: 170, Column: Self_Employed
Row: 218, Column: Self_Employed
Row: 231, Column: Self_Employed
Row: 236, Column: Self_Employed
Row: 268, Column: Self_Employed
Row: 295, Column: Self_Employed
Row: 333, Column: Self_Employed
Row: 336, Column: Self_Employed
Row: 344, Column: Self_Employed
Row: 374, Column: Self_Employed
Row: 380, Column: Self_Employed
Row: 385, Column: Self_Employed
Row: 411, Column: Self_Employed
Row: 432, Column: Self_Employed
Row: 447, Column: Self_Employed
Row: 463, Column: Self_Employed
Row: 468, Column: Self_Employed
Row: 535, Column: Self_Employed
Row: 542, Column: Self_Employed
Row: 579, Column: Self_Employed
Row: 600, Column: Self_Employed
Row: 601, Column: Self_Employed
Row: 0, Column: LoanAmount
Row: 35, Column: LoanAmount
Row: 63, Column: LoanAmount
Row: 81, Column: LoanAmount
Row: 95, Column: LoanAmount
Row: 102, Column: LoanAmount
Row: 103, Column: LoanAmount
Row: 113, Column: LoanAmount
Row: 127, Column: LoanAmount
Row: 202, Column: LoanAmount
Row: 284, Column: LoanAmount
Row: 305, Column: LoanAmount
Row: 322, Column: LoanAmount
Row: 338, Column: LoanAmount
Row: 387, Column: LoanAmount
Row: 435, Column: LoanAmount
Row: 437, Column: LoanAmount
Row: 479, Column: LoanAmount
Row: 524, Column: LoanAmount
Row: 550, Column: LoanAmount
Row: 551, Column: LoanAmount
Row: 605, Column: LoanAmount
Row: 19, Column: Loan_Amount_Term
Row: 36, Column: Loan_Amount_Term
Row: 44, Column: Loan_Amount_Term
Row: 45, Column: Loan_Amount_Term
Row: 73, Column: Loan_Amount_Term
Row: 112, Column: Loan_Amount_Term
Row: 165, Column: Loan_Amount_Term
Row: 197, Column: Loan_Amount_Term
Row: 223, Column: Loan_Amount_Term
Row: 232, Column: Loan_Amount_Term
Row: 335, Column: Loan_Amount_Term
Row: 367, Column: Loan_Amount_Term
Row: 421, Column: Loan_Amount_Term
Row: 423, Column: Loan_Amount_Term
Row: 16, Column: Credit_History
Row: 24, Column: Credit_History
Row: 30, Column: Credit_History
Row: 42, Column: Credit_History
Row: 79, Column: Credit_History
Row: 83, Column: Credit_History
Row: 86, Column: Credit_History
Row: 95, Column: Credit_History
Row: 117, Column: Credit_History
Row: 125, Column: Credit_History
Row: 129, Column: Credit_History
Row: 130, Column: Credit_History
Row: 156, Column: Credit_History
Row: 181, Column: Credit_History
Row: 187, Column: Credit_History
Row: 198, Column: Credit_History
Row: 219, Column: Credit_History
Row: 236, Column: Credit_History
Row: 237, Column: Credit_History
Row: 259, Column: Credit_History
Row: 260, Column: Credit_History
Row: 279, Column: Credit_History
Row: 309, Column: Credit_History
Row: 313, Column: Credit_History
Row: 317, Column: Credit_History
Row: 318, Column: Credit_History
Row: 323, Column: Credit_History
Row: 348, Column: Credit_History
Row: 363, Column: Credit_History
Row: 377, Column: Credit_History
Row: 392, Column: Credit_History
Row: 395, Column: Credit_History
Row: 411, Column: Credit_History
Row: 444, Column: Credit_History
Row: 449, Column: Credit_History
Row: 451, Column: Credit_History
Row: 460, Column: Credit_History
Row: 473, Column: Credit_History
Row: 490, Column: Credit_History
Row: 491, Column: Credit_History
Row: 497, Column: Credit_History
Row: 503, Column: Credit_History
Row: 506, Column: Credit_History
Row: 530, Column: Credit_History
Row: 533, Column: Credit_History
Row: 544, Column: Credit_History
Row: 556, Column: Credit_History
Row: 565, Column: Credit_History
Row: 583, Column: Credit_History
Row: 600, Column: Credit_History

In [31]:
print(df.corr)

<bound method DataFrame.corr of       Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No
1    LP001003    Male     Yes          1      Graduate            No
2    LP001005    Male     Yes          0      Graduate           Yes
3    LP001006    Male     Yes          0  Not Graduate            No
4    LP001008    Male      No          0      Graduate            No
..        ...     ...     ...        ...           ...           ...
609  LP002978  Female      No          0      Graduate            No
610  LP002979    Male     Yes         3+      Graduate            No
611  LP002983    Male     Yes          1      Graduate            No
612  LP002984    Male     Yes          2      Graduate            No
613  LP002990  Female      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0
1               4583             1508.0       128.0             360.0
2               3000                0.0        66.0             360.0
3               2583             2358.0       120.0             360.0
4               6000                0.0       141.0             360.0
..               ...                ...         ...               ...
609             2900                0.0        71.0             360.0
610             4106                0.0        40.0             180.0
611             8072              240.0       253.0             360.0
612             7583                0.0       187.0             360.0
613             4583                0.0       133.0             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]>